### ISSUE TITLE
使用nn.MSELoss()只有零点零几

### ISSUE THREAD

**Issue by meizitt** [CaiCandong/sa_convLSTM#1]
你好，我使用你的模型跑出的loss只有零点零几，和论文中的差距很大，并且预测的效果全是黑色的图片，请问你的也是这样的嘛

**Comment by CaiCandong** [comment]
我也是参考别人的模型 https://github.com/MinNamgung/sa_convlstm
1.这个loss我也不清楚 确实和原论文差别挺大的。
2. 虽然效果比较差，但还是有效果的，不是全黑色的图片。

**Comment by meizitt** [comment]
> 我也是参考别人的模型 https://github.com/MinNamgung/sa_convlstm 1.这个loss我也不清楚 确实和原论文差别挺大的。 2. 虽然效果比较差，但还是有效果的，不是全黑色的图片。

感谢答复

**Comment by liuboniu** [comment]
您好，我以前搭建模型都是直接用keras现成的来调用。由于现在没有现成的SA-ConvLSTM包，我想请问您一下，如果想用您的SA-ConvLSTM函数，我应该怎么训练呢？

**Comment by CaiCandong** [comment]
> 您好，我以前搭建模型都是直接用keras现成的来调用。由于现在没有现成的SA-ConvLSTM包，我想请问您一下，如果想用您的SA-ConvLSTM函数，我应该怎么训练呢？

这个是用Pytorch实现的，你可以找一个Pytorch的demo跑一下，比如手写数字识别啥的，然后把模型和数据换一下就差不多了能跑了吧。

**Comment by liuboniu** [comment]
![image](https://user-images.githubusercontent.com/86708655/202599135-50aac297-917b-4b6f-802a-fc3495bce657.png)
您好，你这个SA-ConvLSTM模型训练的时候输入输出个数是多少？x的大小和SA-ConvLSTM()括号里面的数值有啥关系？

**Comment by CaiCandong** [comment]
输入：批量大小32、序列长度10、通道64(input_dim)、图片高16、图片宽16
输入的通道数要和input_dim对应上。
